# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: site
    schedule:
      interval: weekly
    groups:
      node:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directories:
      - "/"
    schedule:
      interval: weekly
    groups:
      go:
        patterns:
          - "*"
    ignore:
      - dependency-name: "github.com/envoyproxy/gateway"
      # Usually, this requires manual changes to the codebase.
      - dependency-name: "sigs.k8s.io/gateway-api-inference-extension"
