# This is the configuration file for https://github.com/vladopajic/go-test-coverage

profile: ./out/go-test-coverage.out
local-prefix: "github.com/envoyproxy/ai-gateway/"

threshold:
  # Minimum coverage percentage required for individual files.
  file: 70
  # Minimum coverage percentage required for each package.
  package: 80
  # Minimum overall project coverage percentage required.
  total: 95

exclude:
  paths:
    - ^api/
    - ^examples/
    - apischema/
    - cmd/
    - tests/internal/envtest.go
    - internal/controller  # TODO
