// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

package e2e

import (
	"context"
	"encoding/base64"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	"github.com/envoyproxy/ai-gateway/tests/internal/e2elib"
	"github.com/envoyproxy/ai-gateway/tests/internal/testupstreamlib"
)

// Test_DynamicMetadataRateLimit exercises the dynamic per-request rate-limit
// override feature.
//
// The feature: AI Gateway's router ext_proc reads a "<count>/<unit>" string
// from a source filter-metadata namespace/key (configured via
// GatewayConfig.Spec.GlobalRateLimits) and emits a {requests_per_unit, unit}
// struct into io.envoy.ai_gateway[<metadataKey>] dynamic metadata on the
// REQUEST path, so Envoy's global rate limit can gate traffic on a dynamic,
// per-tenant limit rather than the static limit in the BackendTrafficPolicy.
//
// Because the vendored Envoy Gateway (v1.8.1) lacks the native
// BackendTrafficPolicy ...limit.fromMetadata field (envoyproxy/gateway#9216),
// the testdata wires the consumer side with two EnvoyPatchPolicies:
//   - one adds a set_metadata HTTP filter that writes "2/MINUTE" into the
//     source namespace/key (simulating ext_authz), placed before the AI Gateway
//     ext_proc filter in the HCM chain.
//   - one overlays a limit.dynamic_metadata override on the rate-limit action
//     generated by the BackendTrafficPolicy, reading requests_per_unit/unit
//     from io.envoy.ai_gateway[tenant_request_limit].
//
// With the source set to "2/MINUTE", the effective per-tenant limit is 2
// requests per minute: the third request from a given x-tenant-id is rejected
// with HTTP 429 even though the static BackendTrafficPolicy default is 1000/Hour.
func Test_DynamicMetadataRateLimit(t *testing.T) {
	// Apply Redis manifest (shared with the other rate limit tests). The Envoy
	// Gateway global rate limit service (envoy-ratelimit) is backed by Redis.
	require.NoError(t, e2elib.KubectlApplyManifest(t.Context(), "../../examples/token_ratelimit/redis.yaml"))
	t.Cleanup(func() {
		_ = e2elib.KubectlDeleteManifest(context.Background(), "../../examples/token_ratelimit/redis.yaml")
	})

	const manifest = "testdata/dynamic_metadata_ratelimit.yaml"
	require.NoError(t, e2elib.KubectlApplyManifest(t.Context(), manifest))
	t.Cleanup(func() {
		_ = e2elib.KubectlDeleteManifest(context.Background(), manifest)
	})

	const egSelector = "gateway.envoyproxy.io/owning-gateway-name=envoy-ai-gateway-dynamic-ratelimit"
	e2elib.RequireWaitForGatewayPodReady(t, egSelector)

	// Wait for the redis pod to be ready so that the rate limit can be performed
	// correctly. Until the redis pod is ready, envoy-ratelimit will be in
	// CrashLoopBackOff, so restart it to get a clean state up faster.
	require.NoError(t, e2elib.KubectlRestartDeployment(t.Context(), e2elib.EnvoyGatewayNamespace, "envoy-ratelimit"))
	e2elib.RequireWaitForPodReady(t, e2elib.EnvoyGatewayNamespace, "app.kubernetes.io/component=ratelimit")
	e2elib.RequireWaitForPodReady(t, "redis-system", "app=redis")

	const modelName = "dynamic-ratelimit-model"
	makeRequest := func(t *testing.T, tenantID string, expStatus int) {
		fwd := e2elib.RequireNewHTTPPortForwarder(t, e2elib.EnvoyGatewayNamespace, egSelector, e2elib.EnvoyGatewayDefaultServicePort)
		defer fwd.Kill()

		requestBody := fmt.Sprintf(`{"messages":[{"role":"user","content":"Say this is a test"}],"model":"%s"}`, modelName)
		const fakeResponseBody = `{"choices":[{"message":{"content":"This is a test.","role":"assistant"}}],"usage":{"prompt_tokens":1,"completion_tokens":1,"total_tokens":2}}`

		req, err := http.NewRequest(http.MethodPut, fwd.Address()+"/v1/chat/completions", strings.NewReader(requestBody))
		require.NoError(t, err)
		req.Header.Set(testupstreamlib.ResponseBodyHeaderKey, base64.StdEncoding.EncodeToString([]byte(fakeResponseBody)))
		req.Header.Set(testupstreamlib.ExpectedPathHeaderKey, base64.StdEncoding.EncodeToString([]byte("/v1/chat/completions")))
		req.Header.Set("x-tenant-id", tenantID)
		req.Header.Set("Host", "openai.com")

		resp, err := http.DefaultClient.Do(req)
		require.NoError(t, err)
		defer func() { _ = resp.Body.Close() }()

		body, err := io.ReadAll(resp.Body)
		require.NoError(t, err)
		require.Equal(t, expStatus, resp.StatusCode, "unexpected status code, body: %s", string(body))
	}

	// The set_metadata filter writes "2/MINUTE" for every request, so the dynamic
	// limit is 2 requests per minute per unique x-tenant-id. Use a fresh tenant
	// ID per assertion block to avoid collisions with previous runs (rate-limit
	// budgets are tracked in Redis across the test process lifetime).
	baseID := int(time.Now().UnixNano())

	t.Run("dynamic limit gates traffic at 2/MINUTE", func(t *testing.T) {
		tenantID := strconv.Itoa(baseID)
		// The dynamic override caps this tenant at 2 requests/minute. The first two
		// requests are allowed; the third exceeds the dynamic limit and is rejected,
		// proving the limit came from metadata and not the 1000/Hour static default.
		makeRequest(t, tenantID, http.StatusOK)
		makeRequest(t, tenantID, http.StatusOK)
		makeRequest(t, tenantID, http.StatusTooManyRequests)
	})

	t.Run("a different tenant has an independent budget", func(t *testing.T) {
		// A distinct x-tenant-id selector means each tenant gets its own budget, so
		// a fresh tenant is allowed again even after the first one was rate limited.
		tenantID := strconv.Itoa(baseID + 1)
		makeRequest(t, tenantID, http.StatusOK)
		makeRequest(t, tenantID, http.StatusOK)
		makeRequest(t, tenantID, http.StatusTooManyRequests)
	})
}
