# Copyright Envoy AI Gateway Authors
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

# This file contains the base Envoy Gateway helm values needed for AI Gateway integration.
# This is the minimal configuration that all AI Gateway deployments need.
#
# Use this file when installing Envoy Gateway with:
#   helm upgrade -i eg oci://docker.io/envoyproxy/gateway-helm \
#     --version v0.0.0-latest \
#     --namespace envoy-gateway-system \
#     --create-namespace \
#     -f envoy-gateway-values.yaml
#
# For additional features, combine with addon values files:
#   -f envoy-gateway-values.yaml -f examples/token_ratelimit/envoy-gateway-values-addon.yaml
#   -f envoy-gateway-values.yaml -f examples/inference-pool/envoy-gateway-values-addon.yaml

config:
  apiVersion: gateway.envoyproxy.io/v1alpha1
  kind: EnvoyGateway
  gateway:
    controllerName: gateway.envoyproxy.io/gatewayclass-controller
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
  extensionApis:
    enableEnvoyPatchPolicy: true
    enableBackend: true
  extensionManager:
    hooks:
      xdsTranslator:
        translation:
          listener:
            includeAll: true
          route:
            includeAll: true
          cluster:
            includeAll: true
          secret:
            includeAll: true
        post:
          - Translation
          - Cluster
          - Route
    service:
      fqdn:
        # Update this hostname to match your AI Gateway controller service name and namespace
        # Default is ai-gateway-controller.envoy-ai-gateway-system.svc.cluster.local
        hostname: ai-gateway-controller.envoy-ai-gateway-system.svc.cluster.local
        port: 1063
