apiVersion: v2
name: ai-gateway-helm
description: The Helm chart for Envoy AI Gateway
type: application

version: v0.0.0-latest
appVersion: "latest"
# TODO: fix the icon path to AI Gateway logo once it's available.
icon: https://raw.githubusercontent.com/envoyproxy/gateway/main/site/assets/icons/logo.svg

maintainers:
  - name: envoy-gateway-maintainers
    url: https://github.com/envoyproxy/gateway/blob/main/CODEOWNERS

keywords:
  - gateway-api
  - envoyproxy
  - envoy-gateway
  - eg
  - ai-gateway
  - ai

# TODO: update the home URL once the website is available.
home: https://github.com/envoyproxy/ai-gateway

sources:
  - https://github.com/envoyproxy/ai-gateway
