# Copyright Envoy AI Gateway Authors
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: envoy-ai-gateway-gateway-deployment-mutator
webhooks:
  - name:  {{ include "ai-gateway-helm.controller.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    clientConfig:
      service:
        name:  {{ include "ai-gateway-helm.controller.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate
      {{- if .Values.controller.mutatingWebhook.caBundle }}
      caBundle: {{ .Values.controller.mutatingWebhook.caBundle }}
      {{- else }}
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURPekNDQWlPZ0F3SUJBZ0lVVStnMVVwcDFRdGZwazg3elk1SDIvRVk1NVFVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0xURUxNQWtHQTFVRUJoTUNRVlV4SGpBY0JnTlZCQU1NRldGcExXZGhkR1YzWVhrdFkyOXVkSEp2Ykd4bApjakFlRncweU5UQTFNakF4TmpRek5USmFGdzB6TlRBMU1UZ3hOalF6TlRKYU1DMHhDekFKQmdOVkJBWVRBa0ZWCk1SNHdIQVlEVlFRRERCVmhhUzFuWVhSbGQyRjVMV052Ym5SeWIyeHNaWEl3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURLTjVZbU1oN1RnR3FOcGVkQzBEV0JXZG4ycE1pSHRDZVJsVGtsdURqSwpsK1plbGVpUjdyb29OVVhjNmdFMDJSQWFSQ0VhTk1TWkwzbTZCa1oxWG9vOTJNdmFidStPUmt3QXBPK09USXZqCk5zWWIzL2Jsc1NUMXFIWEFwbTduODg2RWQ4MENHM0pjemk3QWlvWHNBaFR2K1NvSmVRSnNvS0xlVllWNW01bC8KajR4b0psOWZZK2x6cG1nZGNBTEJtN0ZEckFic0Vnakt3bUZFUUF4VE54V293WkRpQVJXMjFpbzQ1c2FDNDExUwptL1podGhTeERRcHFTelB3WWNYd1IwNHN5WnhHVWV3WXJwSUU1NGhSc004S3dwcU5FWlZuamxhS0Jzc2lFZ0c4Cjk3c3g5d0RiM0hMemVwN0ZTaEt6NExzbGVQQWM4RG12ZFlqbm9vWmF4enNmQWdNQkFBR2pVekJSTUIwR0ExVWQKRGdRV0JCUzlwdUowaSt6S1c0WTNGWTJOdlJLQWIwT05ZekFmQmdOVkhTTUVHREFXZ0JTOXB1SjBpK3pLVzRZMwpGWTJOdlJLQWIwT05ZekFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNaClpnUENRbmFYdC94U0o3b1VGQk1iYTVUTGVxdnpJS1BlRHZTMGlpNjR0WmVRNzVSN25RdlNWdDJRbkdEanB5SisKMDBFUmphN2pXcGpMM0lXaWptRTE5OXZ2NDBaWTRwYWpoQkFMM3k4d1BmNnZSaDhkN1RPNFhtTjdoc2VyMnRjaQpkZW5OR1B4dTFiWDJ0TEU4RkFHTThTVWFyVnk2dmVIZGlVeW9NbEpXcHZqV1lOZ2FWRTVZeC84MzlXbXhSaG5TCjJJT2xqQXNUd2FJa0kwd21zNTFsWlhHUGhSZ0VTOUFvTFB1eXdzZ3E3R2NqSWhZSHBmc28vM0RnUzgvTVRSNUIKaVdxaVhwZ2pENlpPelRReXA4enBuR3pZR2R4U0theGQxSTBMaExUdWF3ZExRK0RTM3p2UjVTNVY1dkxRVVoxcgowVW44RTY4bjdzOEVwbFY4TjZ4bAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      {{- end }}
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    objectSelector:
      matchLabels:
        app.kubernetes.io/managed-by: envoy-gateway
    sideEffects: None
    admissionReviewVersions: ["v1"]
    timeoutSeconds: 10
    failurePolicy: Ignore
---
apiVersion: v1
kind: Secret
metadata:
  name: self-signed-cert-for-mutating-webhook
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDaTCCAlGgAwIBAgIUHUaEt6oW5HaBSAc/DZZ39PclDaUwDQYJKoZIhvcNAQEL
    BQAwLTELMAkGA1UEBhMCQVUxHjAcBgNVBAMMFWFpLWdhdGV3YXktY29udHJvbGxl
    cjAeFw0yNTA1MjAxNjQ1MzNaFw0zNTA1MTgxNjQ1MzNaMC0xCzAJBgNVBAYTAkFV
    MR4wHAYDVQQDDBVhaS1nYXRld2F5LWNvbnRyb2xsZXIwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQDHhlhQBR2pplNbgA5Q0lvqimzUylfGAeTVPrSQs73L
    Fj2Lqi/ROtyFHdfruRzVMnmWfMWbh57kIv6KEXHkhJngD4rjcWjLQvKZjUKUe9s7
    P1tQ0S9rIzMeBk8dQ3vrm+XcFy9zhuROccpmaXOTjanW9I7Uxl0/fINfc2++nIUx
    8LSJPf845iHJlHF7uuzhRIMD3M0ShXSS8SnPQPicq18mqufczN+8SC5jwDeCAUEM
    67ter1OnXdjuJSSHpRY9Rj32jyIGYEjFTgqV1tU+ut86xzzRMGilcXio1NubJxfH
    IwOWCG82qyddZpGLVHAUapgaW4H5Lce+uELhShc0HiRpAgMBAAGjgYAwfjA8BgNV
    HREENTAzgjFhaS1nYXRld2F5LWNvbnRyb2xsZXIuZW52b3ktYWktZ2F0ZXdheS1z
    eXN0ZW0uc3ZjMB0GA1UdDgQWBBTHtH9TzxZK9i29+djfBe6foVNN4jAfBgNVHSME
    GDAWgBS9puJ0i+zKW4Y3FY2NvRKAb0ONYzANBgkqhkiG9w0BAQsFAAOCAQEAmOKx
    ws4huAPawx1hcZQNNz6TTv6BwxGAVG4WX69Pb3ZWXB/vxPIIPkbhP23oumtn0N7l
    ehy6K89FPDCCeuz9kibsDHQWjl349jPSyGULMVYT2DoI9KKxwFdjgVwF8pOOvBe3
    8tTiPcCoYbssMpmYQKGXiqENrIKTq9dzzqMxkN9a4XNyk2xB9P8RSiv/6sQqE5Ni
    bY6TeD4T8AgaGdHteCeRNBJxaiKPttv9D62zd02lJ9w7BKsphNRDH1dNCNgM8KJE
    Rxf1TRtGZTXfz6y7gFYK1w7RwI9v5JUiRH28RyexeNKmAYlP6pbKN6wM4S0OktyY
    znuy770iwgvtVaugwQ==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDHhlhQBR2pplNb
    gA5Q0lvqimzUylfGAeTVPrSQs73LFj2Lqi/ROtyFHdfruRzVMnmWfMWbh57kIv6K
    EXHkhJngD4rjcWjLQvKZjUKUe9s7P1tQ0S9rIzMeBk8dQ3vrm+XcFy9zhuROccpm
    aXOTjanW9I7Uxl0/fINfc2++nIUx8LSJPf845iHJlHF7uuzhRIMD3M0ShXSS8SnP
    QPicq18mqufczN+8SC5jwDeCAUEM67ter1OnXdjuJSSHpRY9Rj32jyIGYEjFTgqV
    1tU+ut86xzzRMGilcXio1NubJxfHIwOWCG82qyddZpGLVHAUapgaW4H5Lce+uELh
    Shc0HiRpAgMBAAECggEAAe3u5zExeP1Cg5lAqi/qkyFNDZ66TBAjIBvH37lZPcBE
    jpfx9+4/iSsBdkZXPMmM6vNgbtFYLEEZYIjsJsdQfJ3x3CKx3ntSgMEgsnJjK5bA
    gY7QTFMuEJ2DgNcw+NWMWr0/qHiWtxp7GFPvOe9OA+XgBrc3WiCQXakuXLPDRvkW
    SbSurGfzhlPNVSlqRAK/uYYeRFUvjjvuFB77+ozVPCqMxqMDW9ez7y/oMK5Rphl7
    GbBSHjv/aCfN4OKno/xtPup3xaYHXkNLP1ktGCplJoyx6JSqBqYoKXP9sGsbhlif
    xNI2zhB7VRfjQzclS+26zUIK2GhNd4/LI4ZvzB4bjQKBgQDse6MPqrkW2YFJSQOd
    bpghzHfv3P7VCJi5pgneOeH+qgYvWHtXASC6XmHgd7RjIAkmIkI01VGhIQW1Lwzh
    /K/qmmNgyP1MVIpAedYaMBFFV6q9qWaT+AojFp+PnHjuQHtFP9Lx0dtMwvafb821
    mN1i3ZDWmD7wFt1D6nBetDm2tQKBgQDX/d0HjexwhLILboAzgTWgOPjks60+uh4k
    zf/SxdRE6wHaeUuT5disUJD70G52jGQRR5EMazJvSCPDffIsHdId5qM/H1+LuRs9
    RvPttxyZACgghV+M2cOCkQkbwpMe8O7+SHtSQt2hNnkXu9QUOrU01qgXJrSF6WQn
    vCWiDwczZQKBgH5A/+yEXC7bzs9+gMSTX/tje4D+/rpjzY4IHGqdgo+A3K54UdlA
    i+WUMDM0FYV6fAf08F3eqacZxz9VME6SpqTc6kOo6rrOw8TqhykSEpZv2INLpq1H
    FrpnAKcehd3FZUqyaX+bZ7aSvDKg8TWLuF5pJkO7opZxzo3M41NcaxelAoGADnfc
    5HKnUeoxmv5t7AVNuEvYsEkw47DH8CM0bcP+shcj6qSRYXjWCMTk0Vlm7N3+ngGz
    P6e2mymz65Z2MGpW9tXKPaI2Xj+qCXLFSDkp2z3dckA85Ex6AjcA6zEfdcUh3Tqx
    uBLukav6dJKKZEiCduWiINrg4M9/fAHoa3CiRNkCgYEAnEn9gCO4e0raIREBFMRW
    9uiRLb1cc4GvZxYDj4xf0AR99bL599GMe/yMbtaeqhC5z2pVgyRGwxPCmoY5KQrB
    i4X6Yrl37GEpCf94kpkdM6AtzA2DZ9Tfzoai61RKvP1W93vWohjXtv1OZWDuDB+H
    SJhKidoVRcKlB8eLvnwIh+g=
    -----END PRIVATE KEY-----
