# Copyright Envoy AI Gateway Authors
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

---
# This file contains the RBAC roles and role bindings for the Envoy Gateway
# so that it can read the custom resources defined for AI Gateway.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # TODO: this naming is weird and I think it's a remnant of when the project was called ai-gateway-controller
  # at the very beginning of the POC. Though this is harmless, we might want to rename it to something like
  # "access-ai-gateway-resources" or something like that, but that would be a breaking change.
  name: list-ai-gateway-controller
rules:
  - apiGroups:
      - "aigateway.envoyproxy.io"
    resources:
      - "aigatewayroutes"
      - "aiservicebackends"
      - "backendSecurityPolicies"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "inference.networking.k8s.io"
    resources:
      - "inferencepools"
    verbs:
      - "get"
      - "list"
      - "watch"
---
# RBAC RoleBinding to bind the above ClusterRole to the ServiceAccount used by the Envoy Gateway controller.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-ai-gateway-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-ai-gateway-controller
subjects:
  - kind: ServiceAccount
    name: {{ .Values.envoyGateway.serviceAccountName }}
    namespace: {{ .Values.envoyGateway.namespace }}
---
