apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-gateway-helm.controller.fullname" . }}
  labels:
    {{- include "ai-gateway-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  {{- with .Values.controller.service.ports }}
  ports:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "ai-gateway-helm.controller.selectorLabels" . | nindent 4 }}
