# Copyright Envoy AI Gateway Authors
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: envoy-ai-gateway-basic-cohere
  namespace: default
spec:
  parentRefs:
    - name: envoy-ai-gateway-basic
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: rerank-english-v3.0
      backendRefs:
        - name: envoy-ai-gateway-basic-cohere
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: envoy-ai-gateway-basic-cohere
  namespace: default
spec:
  schema:
    name: Cohere
    version: v2
  backendRef:
    name: envoy-ai-gateway-basic-cohere
    kind: Backend
    group: gateway.envoyproxy.io
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: BackendSecurityPolicy
metadata:
  name: envoy-ai-gateway-basic-cohere-apikey
  namespace: default
spec:
  targetRefs:
    - group: aigateway.envoyproxy.io
      kind: AIServiceBackend
      name: envoy-ai-gateway-basic-cohere
  type: APIKey
  apiKey:
    secretRef:
      name: envoy-ai-gateway-basic-cohere-apikey
      namespace: default
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: envoy-ai-gateway-basic-cohere
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: api.cohere.com
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: envoy-ai-gateway-basic-cohere-tls
  namespace: default
spec:
  targetRefs:
    - group: 'gateway.envoyproxy.io'
      kind: Backend
      name: envoy-ai-gateway-basic-cohere
  validation:
    wellKnownCACertificates: "System"
    hostname: api.cohere.com
---
apiVersion: v1
kind: Secret
metadata:
  name: envoy-ai-gateway-basic-cohere-apikey
  namespace: default
type: Opaque
stringData:
  apiKey: COHERE_API_KEY # Replace with your Cohere API key.
