# Copyright Envoy AI Gateway Authors
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIGatewayRoute
metadata:
  name: envoy-ai-gateway-basic-googleai
  namespace: default
spec:
  parentRefs:
    - name: envoy-ai-gateway-basic
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: gemini-2.5-flash-image
      backendRefs:
        - name: envoy-ai-gateway-basic-googleai
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIServiceBackend
metadata:
  name: envoy-ai-gateway-basic-googleai
  namespace: default
spec:
  schema:
    name: GoogleAIStudio
    version: v1beta
  backendRef:
    name: envoy-ai-gateway-basic-googleai
    kind: Backend
    group: gateway.envoyproxy.io
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: BackendSecurityPolicy
metadata:
  name: envoy-ai-gateway-basic-googleai-apikey
  namespace: default
spec:
  targetRefs:
    - group: aigateway.envoyproxy.io
      kind: AIServiceBackend
      name: envoy-ai-gateway-basic-googleai
  type: GoogleAIKey
  googleAIKey:
    secretRef:
      name: envoy-ai-gateway-basic-googleai-apikey
      namespace: default
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: envoy-ai-gateway-basic-googleai
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: generativelanguage.googleapis.com
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: envoy-ai-gateway-basic-googleai-tls
  namespace: default
spec:
  targetRefs:
    - group: "gateway.envoyproxy.io"
      kind: Backend
      name: envoy-ai-gateway-basic-googleai
  validation:
    wellKnownCACertificates: "System"
    hostname: generativelanguage.googleapis.com
---
apiVersion: v1
kind: Secret
metadata:
  name: envoy-ai-gateway-basic-googleai-apikey
  namespace: default
type: Opaque
stringData:
  apiKey: GOOGLE_AI_STUDIO_API_KEY # Replace with your Google AI Studio API key.
