name: Docker Builds Template

on:
  workflow_call:

jobs:
  docker_builds:
    name: ${{ matrix.target.command_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - command_name: "controller"
          - command_name: "extproc"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version-file: go.mod
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
            ~/go/bin
          key: build-container-${{ hashFiles('**/go.mod', '**/go.sum', '**/Makefile') }}

      - uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Login into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Do not build and push images for pull requests. Just build them to ensure the build is successful.
      - name: Build Image
        if: github.event_name != 'push'
        run: |
          make docker-build.${{ matrix.target.command_name }}

      # Push images for the push events, e.g. when a new tag is pushed as well as PR merges.
      # * Only use the tag if the event is a tag event, otherwise use "latest".
      # * Build for both amd64 and arm64 platforms.
      - name: Build and Push Image
        if: github.event_name == 'push'
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="latest"
          fi
          make docker-build.${{ matrix.target.command_name }} ENABLE_MULTI_PLATFORMS=true TAG=$TAG DOCKER_BUILD_ARGS="--push"
