name: PR Style Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read

jobs:
  description:
    name: Description
    runs-on: ubuntu-latest
    steps:
      - name: Check PR description
        env:
          # Do not use ${{ github.event.pull_request.body }} directly in run command.
          BODY: ${{ github.event.pull_request.body }}
        run: |
          if [[ $BODY =~ "<!--" ]]; then
              echo "PR description contains '<!--'. Please remove all the comment out lines in the template after carefully reading them."
              exit 1
          fi
          if [[ $BODY =~ "-->" ]]; then
              echo "PR description contains '-->'. Please remove all the comment out lines in the template after carefully reading them."
              exit 1
          fi
          first_line=$(echo -n "$BODY" | head -n 1)
          trimmed_first_line=$(echo "$first_line" | sed 's/[[:space:]]*$//')
          echo "$trimmed_first_line='$trimmed_first_line'"
          if [[ "$trimmed_first_line" != "**Commit Message**" ]]; then
            echo "The first line of the PR description must be '**Commit Message**'"
            exit 1
          fi

  title:
    name: Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            docs
            style
            feat
            test
            build
            ci
            chore
            revert
            release
            api
            deps
            e2e
            extproc
            controller
            translator
            examples
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
