name: Tests using Secrets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  pull_request_target:
    types: [labeled]
    branches:
      - main

jobs:
  extproc_tests:
    if: ( github.event.pull_request.head.repo.fork == false ) ||
      ( contains(github.event.pull_request.labels.*.name, 'safe to test') )
    runs-on: ubuntu-latest
    steps:
      # The original repo.
      - uses: actions/checkout@v4
        if: >-
          ( github.event_name == 'pull_request' ) &&
          ( github.event.pull_request.head.repo.fork == false )

      # Forked repo.
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
        if: >-
          ( github.event_name == 'pull_request_target' ) &&
          ( github.event.pull_request.head.repo.fork == true )

      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version-file: go.mod

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
          key: extproc-tests-${{ hashFiles('**/go.mod', '**/go.sum', '**/Makefile') }}

      - name: Run unit tests
        env:
          TEST_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_BEDROCK_USER_AWS_ACCESS_KEY_ID }}
          TEST_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_BEDROCK_USER_AWS_SECRET_ACCESS_KEY }}
          TEST_OPENAI_API_KEY: ${{ secrets.ENVOY_AI_GATEWAY_OPENAI_API_KEY }}
        run: make test-extproc-e2e
